# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    access_denied_url: /deny
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    client:
                        password: $2a$06$xVHA9wiVjCqUmCXqSO9HwuaFO99BKoTmUGxDgtOBB8t8w05gbpJxC
                        roles: 'ROLE_CLIENT'
                    user:
                        password: $2a$06$xVHA9wiVjCqUmCXqSO9HwuaFO99BKoTmUGxDgtOBB8t8w05gbpJxC
                        roles: 'ROLE_USER'

                    admin:
                        password: $2a$06$xVHA9wiVjCqUmCXqSO9HwuaFO99BKoTmUGxDgtOBB8t8w05gbpJxC
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            
            logout:
                path:   /logout
                target: /
           
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        # require ROLE_ADMIN for /*
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_ADMIN,ROLE_USER]}

 
